/** DB: ck_tb_admin_audit_log_action */
export const AdminAuditAction = {
  SERVICE_CREATED: 'SERVICE_CREATED',
  SERVICE_UPDATED: 'SERVICE_UPDATED',
  SERVICE_SUSPENDED: 'SERVICE_SUSPENDED',
  SERVICE_RESUMED: 'SERVICE_RESUMED',
  SERVICE_DELETED: 'SERVICE_DELETED',
  API_KEY_ISSUED: 'API_KEY_ISSUED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  PG_CREDENTIAL_REGISTERED: 'PG_CREDENTIAL_REGISTERED',
  PG_CREDENTIAL_DEACTIVATED: 'PG_CREDENTIAL_DEACTIVATED',
  PRODUCT_TYPE_CREATED: 'PRODUCT_TYPE_CREATED',
  PRODUCT_TYPE_UPDATED: 'PRODUCT_TYPE_UPDATED',
  WEBHOOK_CONFIG_UPDATED: 'WEBHOOK_CONFIG_UPDATED',
  WEBHOOK_SECRET_ROTATED: 'WEBHOOK_SECRET_ROTATED',
  WEBHOOK_REDELIVERED: 'WEBHOOK_REDELIVERED',
  PAYMENT_CANCELED_BY_ADMIN: 'PAYMENT_CANCELED_BY_ADMIN',
  PAYMENT_RECONCILED: 'PAYMENT_RECONCILED',
} as const;
export type AdminAuditAction = (typeof AdminAuditAction)[keyof typeof AdminAuditAction];
