/** DB: ck_tb_admin_audit_log_action */
export const AdminAuditAction = {
  SERVICE_CREATED: 'SERVICE_CREATED',
  SERVICE_UPDATED: 'SERVICE_UPDATED',
  SERVICE_SUSPENDED: 'SERVICE_SUSPENDED',
  SERVICE_RESUMED: 'SERVICE_RESUMED',
  SERVICE_DELETED: 'SERVICE_DELETED',
  API_KEY_ISSUED: 'API_KEY_ISSUED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  PG_CREDENTIAL_REGISTERED: 'PG_CREDENTIAL_REGISTERED',
  PG_CREDENTIAL_DEACTIVATED: 'PG_CREDENTIAL_DEACTIVATED',
  PRODUCT_TYPE_CREATED: 'PRODUCT_TYPE_CREATED',
  PRODUCT_TYPE_UPDATED: 'PRODUCT_TYPE_UPDATED',
  WEBHOOK_CONFIG_UPDATED: 'WEBHOOK_CONFIG_UPDATED',
  WEBHOOK_SECRET_ROTATED: 'WEBHOOK_SECRET_ROTATED',
  WEBHOOK_REDELIVERED: 'WEBHOOK_REDELIVERED',
  PAYMENT_CANCELED_BY_ADMIN: 'PAYMENT_CANCELED_BY_ADMIN',
  PAYMENT_RECONCILED: 'PAYMENT_RECONCILED',
} as const;
export type AdminAuditAction = (typeof AdminAuditAction)[keyof typeof AdminAuditAction];

/** 영향이 큰 작업. 사유 없이는 기록(=실행)할 수 없다 → ADMIN_REASON_REQUIRED */
export const REASON_REQUIRED_ACTIONS: ReadonlySet<AdminAuditAction> = new Set([
  AdminAuditAction.SERVICE_SUSPENDED,
  AdminAuditAction.SERVICE_DELETED,
  AdminAuditAction.PG_CREDENTIAL_DEACTIVATED,
  AdminAuditAction.PAYMENT_CANCELED_BY_ADMIN,
]);

/** tb_admin_audit_log.target_type. 코드가 분기하지 않는 값이라 DB CHECK는 없다 */
export const AuditTargetType = {
  SERVICE: 'SERVICE',
  API_KEY: 'API_KEY',
  PG_CREDENTIAL: 'PG_CREDENTIAL',
  PRODUCT_TYPE: 'PRODUCT_TYPE',
  PAYMENT: 'PAYMENT',
  WEBHOOK_DELIVERY: 'WEBHOOK_DELIVERY',
} as const;
export type AuditTargetType = (typeof AuditTargetType)[keyof typeof AuditTargetType];
